### login to user
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{ 
  "email":"hairip100@gmail.com",
  "password":"cocainit"
}

### register a user
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "username":"hai",
  "email":"hairip100@gmail.com",
  "password":"cocainit",
  "confirmPassword":"cocainit"
}

### get all expenses
GET http://localhost:3000/api/v1/expenses
Content-Type: application/json

### add new expenxe
POST http://localhost:3000/api/v1/expenses
Content-Type: application/json

{
  "amount":123,
  "description":"this is desc",
  "date":"11/08/2004",
  "category":"tiền nhà"
}

### add category
POST http://localhost:3000/api/v1/category
Content-Type: application/json

{
   "name":"tiền nhà"
}

### get all category
GET http://localhost:3000/api/v1/categories
Content-Type: application/json

{
  "name":"tiền nhà"
}