### login to user
POST  
Content-Type: application/json

{
  "username":"",
  "email":"",
  "password":""
}

### register a user
POST http://localhost:3000/v1/register
Content-Type: application/json

{
  "username":"",
  "email":"",
  "password":"",
  "confirmPassword":""
}

### add new expenxe
POST http://localhost:3000/api/v1/